### ISSUE TITLE
Error when run hpfeeds-broker

### ISSUE THREAD

**Issue by StarrySai** [hpfeeds/hpfeeds#53]
Error during run it:
```
root@test:/usr/local/bin# ./hpfeeds-broker 
Traceback (most recent call last):
  File "./hpfeeds-broker", line 9, in <module>
    load_entry_point('hpfeeds==3.0.0.dev0', 'console_scripts', 'hpfeeds-broker')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/hpfeeds-3.0.0.dev0-py3.6.egg/hpfeeds/scripts/broker.py", line 7, in <module>
    from hpfeeds.broker.auth import env, json, sqlite
  File "/usr/local/lib/python3.6/dist-packages/hpfeeds-3.0.0.dev0-py3.6.egg/hpfeeds/broker/auth/json.py", line 4, in <module>
    from hpfeeds.broker.utils.inotify import start_watching
  File "/usr/local/lib/python3.6/dist-packages/hpfeeds-3.0.0.dev0-py3.6.egg/hpfeeds/broker/utils/inotify.py", line 14, in <module>
    aionotify.Flags.MODIFY | aionotify.Flags.ATTRIB | aionotify.Flags.MOVE_SELF | aionotify.Flags.DONT_FOLLOW
AttributeError: 'NoneType' object has no attribute 'Flags'
```
Thanks in advance!

**Comment by Jc2k** [comment]
Have hopefully fixed this on master, can you give it a try?

**Comment by StarrySai** [comment]
> Have hopefully fixed this on master, can you give it a try?

I don't understand docker, but I see in the docker file that aionotify needs to be installed, so I installed aionotify with pip and it worked fine.
Now I am learning docker, it seems that it is very valuable to learn.

But I still have a question, I use pip install hpfeeds [broker] and it tells me:
`WARNING: hpfeeds 1.0 does not provide the extra 'broker'`
Later, I installed using git.

I am a newbie and used your hpfeeds on the recommendation of others, so I may have asked some stupid questions, thank you very much.

**Comment by Jc2k** [comment]
`aionotify` is only used by the YAML auth backend so that it can do hot reloads if the auth config changes. It shouldn't be optional, hopefully after d18a533 it is again.

Regarding your other question, another unrelated team have registered `hpfeeds` on pypi. So when you do `pip install hpfeeds[broker]` you installed a random old version of the code that they uploaded.

Most of the public honeypots on python 3 use my old hpfeeds3 package. I don't think there have been any big changes since i merged it back into the main repo so thats fine to do. And i always run the broker from Docker, which builds directly from git.

**Comment by StarrySai** [comment]
Thanks a lot, I understand.
Maybe the last question:
What is the difference between `hpfeeds` and `hpfeeds3`? 
Because `hpfeeds` also supports python3, why should there be `hpfeeds3`?

**Comment by Jc2k** [comment]
Good question.

When i made hpfeeds3 i had no interest in supporting python 2 and hpfeeds itself wasn't maintained. But one of the first things i did was to add tests, so i was able to preserve python 2 support without too much pain. This meant hpfeeds3 was able to be merged back into the hpfeeds repo. This meant as of may hpfeeds==hpfeeds3, and since then the only changes have been to the broker (and they have been minor).

Right now `hpfeeds3` would be archived but until the pypi ownership of `hpfeeds` is resolved i might need to do releases for the honeypots that currently already depend on `hpfeeds3`.

If we are able to resolve the package name ownership then i'll archive `hpfeeds3` and reach out to the sensors i know of and get them to switch their dependency back to `hpfeeds`.

**Comment by StarrySai** [comment]
I use hpfeeds, I support hpfeeds, justice will come eventually.
Good luck.
