### ISSUE TITLE
Getting exception in feedbroker.py

### ISSUE THREAD

**Issue by prashantvidja** [hpfeeds/hpfeeds#55]
Hello,

When I send an event from the client to the hp-feed broker then it will get below exception in feedbroker.py

> INFO:root:Auth success by test.
> Traceback (most recent call last):
>   File "/opt/hpfeeds/env/src/evnet-dev/evnet/__init__.py", line 569, in _readable
>     self._event('read', data)
>   File "/opt/hpfeeds/env/src/evnet-dev/evnet/util.py", line 16, in _event
>     cb(*args)
>   File "/opt/hpfeeds/env/src/evnet-dev/evnet/mongodb.py", line 118, in read
>     p._resolve(buf)
>   File "/opt/hpfeeds/env/src/evnet-dev/evnet/promise.py", line 73, in _resolve
>     self._call_callbacks()
>   File "/opt/hpfeeds/env/src/evnet-dev/evnet/promise.py", line 33, in _call_callbacks
>     fn(self._result, *args, **kwargs)
>   File "feedbroker.py", line 117, in checkauth
>     self.io_in(b'')
>   File "feedbroker.py", line 145, in io_in
>     self.error('accessfail.')
>   File "feedbroker.py", line 193, in error
>     self.conn.write(self.msgerror(emsg))
>   File "/opt/hpfeeds/env/src/evnet-dev/evnet/__init__.py", line 505, in write
>     raise EVException('Already closed.')
> EVException: Already closed.

and at the command line.

> (env) root@ubuntu_fresh:/opt# hpfeeds-client -i test -s 12345 --host localhost -p 10000 -c status.events publish "{hello}"
> Traceback (most recent call last):
>   File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
>     self.s.connect((addr, self.port))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> error: [Errno 111] Connection refused
> [feedcli] connected to @hp2
> got error from server: accessfail.
> [feedcli] closing connection.

Before it was working fine.

Thanks

**Comment by Jc2k** [comment]
Hello

Unfortunately, based on the tracebacks I'm not sure I can help.

The first traceback looks like it is from a verrrry old hpfeeds broker. The broker hasn't used evnet since 2014 - indeed `feedbroker.py` was deleted from the repo on Jun 4 2014. Since then it was ported to gevent and since then ported to python 3 and asyncio. I don't think there is anyone still around who has even used the evnet version.

It also looks like you are using hpfeeds from pypi. That also hasn't been updated since May 2015. There has been a change in maintainership and we are working on resolving that (see #54). In the meantime there are a bunch of fixes in git, and I have released some of them in the `hpfeeds3` pypi package until we can get #54 resolved. Though this mostly looks like an issue with your broker from what I can tell.

**Comment by prashantvidja** [comment]
Yeah I am using https://github.com/pwnlandia/hpfeeds
That's why I am getting this issue.
Thanks now it is resolved.
