### ISSUE TITLE
Problems running a broker

### ISSUE THREAD

**Issue by bontchev** [hpfeeds/hpfeeds#62]
I'm making an HPFeeds plugin for one of my honeypots and I needed a broker running, so I could test it. Unfortunately, I am hitting an endless string of troubles.

1. I can't run the thing at all on my Windows machine, because it has only Python 2.7 and the broker requires Python 3.
2. I can't even run it in a Docker instance on my Windows machine, because for some reason, Docker doesn't install there.
3. Switching to my Ubuntu 16.04 Linux machine, its Python 3 is version 3.5.2. Sadly, the broker uses f-strings, which were introduced in Python 3.6, so it wouldn't run there, either.
4. I set up a VM with Python 3.8.2 and installed the broker there with pip. As per the [documentation](https://python.hpfeeds.org/en/latest/broker.html), trying to run the broker there as

```
hpfeeds-broker -e tcp:port=10000 --name mybroker
```

and then trying to subscribe to a channel (again example from the documentation)

```
hpfeeds subscribe --host localhost -p 10000 -i myident -s mysecret -c mychannel
```

results in a failure to connect and a crash with a stack trace of the client:

```
[2020-05-19 16:15:24,111] [INFO] connecting to localhost:10000
[2020-05-19 16:15:25,148] [ERROR] Could not connect to broker localhost[::1]
Traceback (most recent call last):
  File "c:\python\lib\site-packages\hpfeeds\client.py", line 120, in connect
    self.s.connect((addr, self.port))
  File "c:\python\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10061] No connection could be made because the target machine actively refused it
[feedcli] connected to mybroker
[feedcli] Error message from broker: Authentication failed for myident
[2020-05-19 16:15:25,256] [INFO] Stopped, exiting run loop.
[feedcli] closing connection.
```

OK, I presume the failure to connect was caused by the broker not having an identity database? Well, why doesn't the documentation clearly say that one has to make that first before running the client? And why does the client crash?!

Very well, let's try to make an identity database. Since this is just a test, let's use the JSON method. I created a file `users.json` with the following contents

```json
{
	"reader":
	{
		"owner": "bontchev",
		"secret": "foobar",
		"subchans":
		[
			"elasticpot"
		],
		"pubchans":
		[
		]
	},
	"writer":
	{
		"owner": "bontchev",
		"secret": "foobar",
		"subchans":
		[
		],
		"pubchans":
		[
			"elasticpot"
		]
	}
}
```

Now, WTF is an "owner" and why the hell isn't that explained in the documentation?! Anyway, moving on. Next thing to try

```
hpfeeds-broker -e tcp:port=10000 --name mybroker --auth=users.json
```

and trying to publish to a channel with one of the created identities:

```
hpfeeds publish --host localhost -p 10000 -i writer -s foobar -c elasticpot '{"event": "ping"}'
```

Same goddamn thing - client cannot connect to the broker and crashes with a stack trace. What on Earth is going on?!

Oh, BTW, trying to stop the broker with Ctrl-C results in a crash and stack trace:

```
ERROR:asyncio:Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "c:\users\bontchev\miniconda2\envs\hpfbroker\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\bontchev\miniconda2\envs\hpfbroker\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "c:\users\bontchev\miniconda2\envs\hpfbroker\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\bontchev\miniconda2\envs\hpfbroker\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
INFO:aiorun:Closing the loop.
INFO:aiorun:Leaving. Bye!
```

Have you guys heard of this newfangled concept called "exiting a program gracefully"? Nevermind.

OK, so maybe something is wrong with the installation on that Windows VM, or God knows what. Let's try the Docker instance (on the Linux machine, because Docker doesn't like my Windows machine, remember?). After all, the whole concept of Docker is glorifying the developer's idea of "it runs on my machine".

So, we create a file `docker-compose.yml` as per the documentation:

```
version: '2.1'

volumes:
  hpfeeds_userdb: {}

services:
  hpfeeds:
    image: hpfeeds/hpfeeds-broker
    container_name: hpfeeds
    ports:
     - "0.0.0.0:10000:10000"
    volumes:
     - hpfeeds_userdb:/app/var
```

and run

```
docker-compose run --rm hpfeeds sqlite3 sqlite.db
```

which the documentation warns us will give us an SQLite3 prompt and we'll have to create the identity database. I'll get to that later.

Too bad, so sad, we get an error message instead

```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

Apparently, not only the Python 3 version on my Ubunty machine is no good, but even the Docker version is no good. OK, let's try "2.0" instead of "2.1", as the error message suggests.

We're greeted by another error message, which this time says

```
ERROR: Named volume "hpfeeds_userdb:/app/var:rw" is used in service "hpfeeds" but no declaration was found in the volumes section.
```

WTF?! Isn't that Docker image supposed to work anywhere?! After a lot of blind experimentation, I discovered that it is the `volumes:` definition that is causing the problem. If it is removed, the image runs. Admittedly, there is a version without it in the documentation, but the example just before the authentication section contains it, so I assumed this was the path where the identities database was assumed to be stored on the image? Whatever.

So, without the volumes definition, we're indeed dropped to the SQLite3 prompt. And now fucking what? Presumably, we are supposed to create the identity database. I don't know if you've heard that, folks, but in order to create a database, you need a schema for it. What are the tables, the rows, the data types... Where the hell is the database schema in the documentation?!

(Forgive my French but I am getting really frustrated at this point...)

The example that shows how to insert a user seems to assume that at least one table named `authkeys` exists in the database, and that it contains at least the columns `owner`, `ident`, `secret`, `pubchans`, and `subchans`, so let's create that. Unfortunately, since there is no goddamn schema, we can only guess what the types of these columns are. Here is my best guess:

```
CREATE TABLE IF NOT EXISTS authkeys (
  owner CHAR(50),
  ident CHAR(50),
  secret CHAR(50),
  pubchans VARCHAR(255),
  subchans VARCHAR(255)
);
```

Now let's fill it with the same data we previously tried to supply via a JSON file:

```
INSERT INTO authkeys (owner, ident, secret, pubchans, subchans) VALUES ('bontchev', 'writer', 'foobar', '["elasticpot"]', '[]');
INSERT INTO authkeys (owner, ident, secret, pubchans, subchans) VALUES ('bontchev', 'reader', 'foobar', '[]', '["elasticpot"]');
```

I have no idea if I have guessed correctly what the format of `subchans` and `pubchans` is, but let's verify that the stuff is actually there:

```
SELECT * FROM authkeys;
```

produces

```
bontchev|writer|foobar|["elasticpot"]|[]
bontchev|reader|foobar|[]|["elasticpot"]
```

so the stuff is really there. If the channel format is wrong, we won't be able to publish or subscribe but at least we'll be able to connect, right? Let's give it a try:

```
docker-compose up -d
```

results in

```
Creating hpfeeds
```

so maybe all is well? Well, let's try to ping something with the client:

```
hpfeeds publish --host localhost -p 10000 -i writer -s foobar -c elasticpot '{"event": "ping"}'
```

results in

```
[2020-05-19 16:52:46,478] [INFO] connecting to localhost:10000
[2020-05-19 16:52:46,484] [ERROR] Expected OP_INFO but cannot assemble complete message
```

And that's it. At this point I ran out of ideas and had to give up. This thing doesn't work, it crashes all the time, the documentation is awful, misleading, and missing half of the important info.

I hear that some people are actually managing to collect data from their honeypots with this thing but I am afraid I won't be one of them. Personally, I would be ashamed to release publicly something that is in _this_ sorry state.

**Comment by bontchev** [comment]
OK, I finally managed to get the dockerized instance of the broker to work by using authentication via environment variables instead of via SQLite3 database or a JSON file. That was enough to test and make sure that my own code works (it does).

Of course, the Twisted implementation of the client is crap too and floods the logs with messages like

```
[2020-05-19 15:55:25.644000Z] Scheduling retry 1 to connect <HostnameEndpoint computer-name:port> in 2.401670786 seconds.
```

but whatever. I'm not going to use this crap; I just wanted to make sure that my code works. Let whoever decides to use it care about the rest.

Closing this issue now since if I never ever have to deal with HPFeeds again, it would be too soon...

But you guys really ought to take a good hard look at the awful documentation and at your code that keeps crashing with a stack trace at the smallest whiff of trouble.

**Comment by Jc2k** [comment]
I tried to reach out and help on twitter but my account is private and I'm guessing you couldn't see it.  I'm really sorry you are having such a hard time with this. As a developer nothing is more upsetting than when your code makes someone so upset and angry. I'm really am sad to see you so riled up. I have been there. But I do wish I had had a way to contact you sooner as I likely could have saved you a lot of trouble.

And it's such well written issue too. It's great to finally have some feedback, even if it is hard to hear so much French. I work with a lot of volunteer open source projects and tickets like this are often completely lacking in detail. There is a lot of directly actionable stuff here. There is no one working on hpfeeds full time, its 10 years old and its lucky if it gets a day in a given year. It clearly shows! So detailed breakdowns like this really help focus our energy when we do have a bit of spare time. Especially when it's working so well for our use cases it's easy to miss other people are having a hard time.

> I can't run the thing at all on my Windows machine, because it has only Python 2.7 and the broker requires Python 3.

Indeed. Python 2 is no longer supported by the Python team, and the broker uses asyncio now anyway. (It used to use gevent which was simpler but had data races at the scale we ran it). Windows is not supported anyway.

I have now made it clear at the top of the docs that Windows is not supported and python 3.6 is required.

> I can't even run it in a Docker instance on my Windows machine, because for some reason, Docker doesn't install there.

Annoying. Just so I understand, you can't install it at all. So it's a Docker problem, not a problem with the hpfeeds or the hpfeeds image?

> Switching to my Ubuntu 16.04 Linux machine, its Python 3 is version 3.5.2. Sadly, the broker uses f-strings, which were introduced in Python 3.6, so it wouldn't run there, either.

With the py3 port care was taken to retain py2 support in the clients, but the broker just used whatever was reasonably widely available. IIRC there are other reasons 3.5 isn't supported now, f-strings are just what you notice first because they are a syntax error. 

>    I set up a VM with Python 3.8.2 and installed the broker there with pip. As per the documentation, trying to run the broker there as
>
> hpfeeds-broker -e tcp:port=10000 --name mybroker
> 
> and then trying to subscribe to a channel (again example from the documentation)
>
> hpfeeds subscribe --host localhost -p 10000 -i myident -s mysecret -c mychannel
> 
> results in a failure to connect and a crash with a stack trace of the client:
> 
> [2020-05-19 16:15:24,111] [INFO] connecting to localhost:10000
> [2020-05-19 16:15:25,148] [ERROR] Could not connect to broker localhost[::1]
> Traceback (most recent call last):
>   File "c:\python\lib\site-packages\hpfeeds\client.py", line 120, in connect
>     self.s.connect((addr, self.port))
>   File "c:\python\lib\socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> error: [Errno 10061] No connection could be made because the target machine actively refused it
> [feedcli] connected to mybroker
> [feedcli] Error message from broker: Authentication failed for myident
> [2020-05-19 16:15:25,256] [INFO] Stopped, exiting run loop.
> [feedcli] closing connection.
>
>  OK, I presume the failure to connect was caused by the broker not having an identity database? Well, why doesn't the documentation clearly say that one has to make that first before running the client? And why does the client crash?!

Agree the docs could do a better job of holding peoples hands through their first hpfeeds experience here. It was documented later what you had to do, but not made explicit enough in that first example that there is always an auth store and the default is sqlite. I have just got rid of the first example on the broker page, and switched it to use the easiest authentication backend (env).

BTW, the client didn't crash. It logged an exception. The exception is a windows specific error as far as I can tell. If I had to guess, your localhost resolves to 127.0.0.1 and ::1, but the broker is only listening on the ipv4 form. At this point the broker was in docker still? So that kind of tracks. So it logged an error connecting to v6 because it has never seen a Windows 10061 error before, then managed to connect to v4. Having never ran the code on Windows i'm surprised it went that well, TBH.

> Very well, let's try to make an identity database. Since this is just a test, let's use the JSON method. I created a file users.json with the following contents

<snip>

> Now, WTF is an "owner" and why the hell isn't that explained in the documentation?! Anyway, moving on. Next thing to try

I have no idea what an owner is either. I think it is left over from hpfriends. It's not used for anything, but left in there for backwards compatibility reasons. Have raised #63 to make it optional at the least.

> hpfeeds-broker -e tcp:port=10000 --name mybroker --auth=users.json
>
> and trying to publish to a channel with one of the created identities:
>
> hpfeeds publish --host localhost -p 10000 -i writer -s foobar -c elasticpot '{"event": "ping"}'
>
> Same goddamn thing - client cannot connect to the broker and crashes with a stack trace. What on Earth is going on?!

You didn't post the message, but again - if the same as above the exception that was logged was harmless. It just didn't know what the Windows error meant so logged it. I don't know what else went wrong here. I used the examples you posted and it worked first time (on a Mac). The broker said:

```
WARNING:hpfeeds.broker.utils.inotify:Changes to 'users.json' will not be detected as aionotify is not installed
INFO:hpfeeds.broker.auth.json:Attempting to reload user database
INFO:hpfeeds.broker.auth.json:User database reloaded, 2 users loaded
```

And the client:

```
hpfeeds publish --host localhost -p 10000 -i writer -s foobar -c elasticpot '{"event": "ping"}'
[2020-05-19 16:43:19,731] [INFO] connecting to localhost:10000
[feedcli] connected to mybroker
[feedcli] closing connection.
```

> Oh, BTW, trying to stop the broker with Ctrl-C results in a crash and stack trace:

> .. snip ..

> Have you guys heard of this newfangled concept called "exiting a program gracefully"? Nevermind.

Colorful linguistic constructs aside, that stack trace again features a Windows exception, and thus obviously one the broker has never seen before. This code has never been run on Windows before. It does exist gracefully on macOS or Linux.

> OK, so maybe something is wrong with the installation on that Windows VM, or God knows what. Let's try the Docker instance (on the Linux machine, because Docker doesn't like my Windows machine, remember?). After all, the whole concept of Docker is glorifying the developer's idea of "it runs on my machine".

I've never used Docker on Windows. Sorry it is such a terrible experience. I believed the hype too, so deflated to here it's BS. It's been pretty good between macOS and Linux for me.

> So, we create a file docker-compose.yml as per the documentation:
>
> .. snip ..
>
> and run
>
> docker-compose run --rm hpfeeds sqlite3 sqlite.db
>
>
> which the documentation warns us will give us an SQLite3 prompt and we'll have to create  the identity database. I'll get to that later.
>
> snip snip snip

The yaml you posted here worked first time for me, using the rolling stable release of Docker. The examples were written against the stable release as at a few years ago. So I'm sorry the version included in Ubuntu 16.04 seems to be too old to work with the example config I gave in the docs. For now i've made a note in the docs that we expect a version able to use 2.1 files.

> ERROR: Named volume "hpfeeds_userdb:/app/var:rw" is used in service "hpfeeds" but no declaration was found in the volumes section.

When I dropped the version to 2.0 this didn't happen to me. The only way I could recreate it was to delete these 2 lines:

```
volumes:
  hpfeeds_userdb: {}
```

You see later in the file we explicitly tell docker to us `hpfeeds_userdb`. So without 2 lines docker-compose doesn't know where to put the data anymore, so throws that error. (Yes the docker yaml is crappy here, that `{}` means 'a local persistent volume' is magical and frustrating if you don't known docker). This isn't a problem with hpfeeds though, it's a problem with the contents of the docker-compose file. I can't see any like that in the docs as it stands, but if i'm wrong i'd definitely like to get them fixed.

> WTF?! Isn't that Docker image supposed to work anywhere?! After a lot of blind experimentation, I discovered that it is the volumes: definition that is causing the problem. If it is removed, the image runs. Admittedly, there is a version without it in the documentation, but the example just before the authentication section contains it, so I assumed this was the path where the identities database was assumed to be stored on the image? Whatever.

Not all backends need the auth sqlite database, which is why not every example specifies the volume stuff. If you use the sqlite auth backend and don't specify a volume then the location of the sqlite database is inside the ephemeral bit of container. Great for testing. Not so great for preserving your data. I tried to make the examples in other sections shorter so it was easier to see what was added to support a given feature, but i'll have a think but if that is adding to the confusion then it will need a rethink

> So, without the volumes definition, we're indeed dropped to the SQLite3 prompt. And now fucking what? Presumably, we are supposed to create the identity database. I don't know if you've heard that, folks, but in order to create a database, you need a schema for it. What are the tables, the rows, the data types... Where the hell is the database schema in the documentation?!

The docs weren't clear enough at all here, and this is where I wish I could have stepped in sooner. They were missing a line that told you to start the broker. You see of course you are not meant to make your own schema. The broker creates an empty schema when it starts, which you can then modify at runtime. I have made it explict that this happens now. 

> (Forgive my French but I am getting really frustrated at this point...)

I think you were long ago ;)

> .. snipped .. because don't need to make own schema

> Now let's fill it with the same data we previously tried to supply via a JSON file:

Looks good.

>  ... snip ...

> hpfeeds publish --host localhost -p 10000 -i writer -s foobar -c elasticpot '{"event": "ping"}'
>
> results in
>
> [2020-05-19 16:52:46,478] [INFO] connecting to localhost:10000
> [2020-05-19 16:52:46,484] [ERROR] Expected OP_INFO but cannot assemble complete message
>
> And that's it. At this point I ran out of ideas and had to give up. This thing doesn't work, it crashes all the time, the documentation is awful, misleading, and missing half of the important info.

Honestly you had a pretty shit time here. And you came so close a bunch of times. But ultimately the documentation didn't make it explicit you shouldn't be using Windows. And they assumed a certain level of Docker experience. And that's on me. I've tried to quickly rectify the worst of that, and make a few things more explicit. When I have time i'll try and run through the examples and document the exact setup they are tested with as well.

I'll try harder to match the docs to the audience in future. I didn't want to insult people with Docker basics, but it's clear I should have said a little bit more than I did.

Don't worry about the "crashes". The ones you posted here might look scary and make it look like I don't know what i'm doing, but for a starters they aren't really crashes. When an I/O operation yields an unknown exception a catch all handler should handle it gracefully in terms of retrying, but it will still log it verbosely so that I can potentially add a more explicit handler. None of the stack traces you posted were actually crashes.

> I hear that some people are actually managing to collect data from their honeypots with this thing but I am afraid I won't be one of them. Personally, I would be ashamed to release publicly something that is in this sorry state.

It definitely does seem like it's a dogs breakfast on Windows. Again, i'm sorry the docs didn't flag that before you wasted all that time. And i'm sorry the Docker experience on WIndows is shit. And i'm sorry the docs don't cover the version of docker-compose in Ubuntu 16.04.

When I first saw your tweets I was alarmed and worried master was broken. When I saw your ticket I was almost ashamed. A twitter celebrity says some 10 year old code you have ported to python 3 is shit!

But actually no, i'm definitely not ashamed. For me, and apparently others you have spoken to, it works just fine.

A lot of this is just Docker for Windows issues or outright Windows incompatibility. What's left were tiny nudges in the documentation (like the fact that it creates an empty db for you).

**Comment by Jc2k** [comment]
RE your twisted error. That comes from twisted itself.  It's part of the automatic retrying in twisted endpoints. If you are saying you know how to stop twisted logging that then I would be interested to know.

**Comment by bontchev** [comment]
Well, had the documentation clearly mentioned that the broker can't run on Windows, it certainly would have saved me a day or two of banging my head onto a wall.

However, since it _can_ be installed on Windows (if Python 3.6+ is there), may I suggest that the code checks the OS and clearly reports to the user that it is not capable of running on it?

Yes, Docker refusing to install on my machine is either a problem of my machine or of Docker. When I start the installer for Windows, it displays a simple OK message box that looks like some Java error. Not being sufficiently familiar with Java, I can't make heads or tails of it. Anyway, at least that particular part is not your problem.

Re Python versions. In my own code I make sure to support at least Python 2.6. Ubuntu 16.04 is still supported, meaning that there is pretty good reason to support the latest available versions of whatever is available for it. In the case of Python, that's version 3.5.2. I know that f-strings are faster and more efficient, but compatibility is more important.

Crash or exception is semantic. Well-behaved programs should trap errors and report them nicely to the user and not let the underlying language or OS display technical gobbledegook that looks like a panic.

No, the broker wasn't in Docker. As I said, Docker doesn't install on my machine. It was running on a Win7 VM with Python 3.8.2 installed.

What do you mean by "I didn't post the message"? Isn't '{"event": "ping"}' the message? At least that's what was posted when I finally managed to get the broker to work.

> The broker creates an empty schema when it starts, which you can then modify at runtime.

No, it didn't. The whole `authkeys` table was not there. I had to create it first, before I could start inserting stuff in it. Not that it helped.

Regarding the documentation. Documenting that "it doesn't work" or "requires a higher version" is not the best solution. The best solution is to have your software check for these things and issue meaningful error messages to the user. For instance, [one of my programs](https://gist.github.com/bontchev/8dc7f37207ba76ed71a9576ad65e0dcd) uses the module `olefile`. That's a pretty standard module, installable with `pip`. Do I do

```python
import olefile
```

? Fuck, no! The user cannot be expected to have had it previously installed and a goodamn stack trace because it couldn't be found is not a nice way to tell him that. So, instead I'm doing

```python
try:
    import olefile
except ImportError:
    print('Module "olefile" is not installed. Try "pip install olefile".', file=sys.stderr)
    sys.exit(-1)
```

_This_ is what I meant by "failing gracefully". I similarly intercept import errors and import the right module in those cases when Python 3 requires something different from Python 2.

A few other suggestions about the documentation:

- Split the text in two parts - using the program installed with `pip` from the command line, and using the Docker image. Has to be written in such a way, that the user who decides on one of these two methods finds _all_ the relevant information in the corresponding section.
- Document _everything_. Every command-line option. Every environment variable. Every goddamn thing. Even if you thought the user would never need them. If the program's behavior is impacted by it, document it!

> It definitely does seem like it's a dogs breakfast on Windows.

I was a dog's breakfast on Linux, too. At least the client worked on both OSes.

> And i'm sorry the Docker experience on WIndows is shit.

I didn't _have_ any Docker experience on Windows. It doesn't even start installing, let alone working, let alone giving me any experience with it.

> If you are saying you know how to stop twisted logging that then I would be interested to know.

No, I'm not saying that. I'm saying that the problem is not in my code and since I am not going to use it anyway, let those who would use it care about it.

**Comment by Jc2k** [comment]
I wasn't expecting a reply, much less such a thorough one. Thanks for getting back to me.

So before I reply to any of your technical points I think I need to be clear I didn't make hpfeeds. It's a decade old now, more or less. A couple of years ago I needed a bunch of honeypot types running for a project, and hpfeeds was a common ingest pipeline setup. In some ways I found myself in the same place you were. I thought it was odd that they hadn't used something off the shelf, "a real broker", but it was an old project and had clearly worked for a lot of people before me. I liked the idea of different people coming together and working together to be a nice one. I installed the broker (which had no documentation at that time) and got a few hundred cowrie running against it. At that point there were enough events that it hit a race in the broker because of how it used gevent. 2 streams could be interleaved causing corruption. Worst, the client couldn't detect this case, the protocol parser couldn't recover and it and would think there was a 2GB event and read 2GB of data into RAM. So i fixed it. I saw a lot of stuff like what you are reporting and I fixed it.

It worked well for the project i needed it for, it wasn't perfect, but it worked for me. It worked for others. I pushed my changes upstream and as no one else had any time I said I would try to help others that find themselves in the same shoes as me.

Why do I say all this? I answer questions here because I got as stuck as you did and I did something about it, not because i'm a proud author or trying to sell something. A consequence of this is I just don't have time to get hpfeeds to the level of a modern well documented python project. The best I can do is help nudge other people in the right direction when they get stuck. Naively I wanted to do the nice thing and help people.

I'm going to turn some of your feedback into tickets, if I get time to work on hpfeeds again in the future i'll pick them up while i'm in there, otherwise maybe another kind volunteer will pick them up.

Good day.

**Comment by bontchev** [comment]
>  I thought it was odd that they hadn't used something off the shelf, "a real broker"

Can you suggest one? I might hit that point one day. Currently all my honeypots of different kinds run on the same machine and each writes to a different MySQL database served by a single server at `localhost`. But if I ever get multiple honeypots (of the same kind) running on different machines, each connecting to the MySQL server over the Internet, that won't cut it. I'd need something to send the data to the collector machine, something there to receive it and talk to the MySQL server on it locally.

I dread the thought of doing this with HPFeeds. At one time I examined multiple honeypots and each could _send_ data via an HPFeeds output plugin, but I couldn't find a proper description how to set up a server (recipient) at the time; only MHN seemed to use it and I couldn't make heads or tails of it.

The alternative would be to use Elasticsearch instead of MySQL, and I've had horrible experience with _that_ crap. Basically, each time we had a power failure (a common occurrence here), the whole database became corrupted and unusable. Not just some information in it - ELK simply could no longer use it and it had to be re-created from scratch.

After you emphasized many times that this thing doesn't work on Windows (and I can't get Docker to work on my Windows machine), I decided to try it on Linux again. And, nope, it definitely doesn't work properly. Here's a detailed report.

First, I managed to get a Docker instance with the defined volume to work; not sure why it was failing before. File `docker-compose.yml`:

```dockerfile
version: '2.0'

volumes:
  hpfeeds_userdb: {}

services:
  hpfeeds:
    image: hpfeeds/hpfeeds-broker
    container_name: hpfeeds
    ports:
     - "0.0.0.0:10000:10000"
    volumes:
     - hpfeeds_userdb:/app/var
```

Let's get to the SQLite prompt and create some entries;

```
$ docker-compose run --rm hpfeeds sqlite3 sqlite.db
Creating network "downloads_default" with the default driver
SQLite version 3.30.1 2019-10-10 20:19:45
Enter ".help" for usage hints.
sqlite>
```

So far, so good. Is the database there, does it have the required table with a sensible schema?

```
sqlite> .databases
main: /app/var/sqlite.db
sqlite> .tables
authkeys  logs      stats
sqlite> .schema authkeys
CREATE TABLE authkeys (id integer primary key autoincrement,
                    owner TEXT, ident TEXT, secret TEXT,
                    pubchans TEXT, subchans TEXT);
```

Yay, it does. Let's put something inside:

```
INSERT INTO authkeys (owner, ident, secret, pubchans, subchans) VALUES ('bontchev', 'writer', 'foobar', '["elasticpot"]', '[]');
INSERT INTO authkeys (owner, ident, secret, pubchans, subchans) VALUES ('bontchev', 'reader', 'foobar', '[]', '["elasticpot"]');
```

Is it there?

```
sqlite> select * from authkeys;
1|bontchev|writer|foobar|["elasticpot"]|[]
2|bontchev|reader|foobar|[]|["elasticpot"]
```

Yay, it is. Let's get out and try to use it:

```
sqlite> .exit
$ docker-compose down
Removing network downloads_default
$ docker-compose up -d
Creating network "downloads_default" with the default driver
Creating hpfeeds
$ hpfeeds subscribe --host localhost -p 10000 -i reader -s foobar -c elasticpot
[2020-05-22 17:00:33,724] [INFO] connecting to localhost:10000
[2020-05-22 17:00:33,734] [ERROR] Expected OP_INFO but cannot assemble complete message
```

Weird error messages repeated ad infinitum without a good explanation. Let's try to publish something anyway?

```
$ hpfeeds publish --host localhost -p 10000 -i writer -s foobar -c elasticpot '{"event": "ping"}'
[2020-05-22 17:04:35,300] [INFO] connecting to localhost:10000
[2020-05-22 17:04:35,302] [ERROR] Expected OP_INFO but cannot assemble complete message
```

Same crap. I give up and once more find myself frustrated and regretting to have wasted my time on this thing. The only thing that worked was authentication via environment variables. I don't have a Mongo database to play with - and neither do I have the wish to do it, to be honest.

**Comment by bontchev** [comment]
Yeah, I've heard good things about Kafka. Colleagues of mine in Iceland are using it. Started looking at it once but gave up - seemed way too complicated. Still, will probably end up using that if I have to. I'll cross that bridge when/if I reach it. It definitely doesn't seem like something I'd like to be messing with just for fun...

Using front-ends to the honeypots - dunno, I've never done that. I'll give it some thought.

The HPFeeds broker in Go - no, thanks. I know I'm probably weird, but I prefer to read the documentation before I start messing with a program. Since in this case there isn't any... Besides, I don't know Go; I wouldn't even know how to compile this thing.

Regarding the bug - could it be some kind of Python incompatibility? I'm running the client on the Ubuntu machine, which has Python 2.7.12 and 3.5.2. Both have the hpfeeds client installed with `pip`; not sure which one is used when I run `hpfeeds` from the command line. Probably the one for Python 3, judging by the hashbang.
