### ISSUE TITLE
async usage

### ISSUE THREAD

**Issue by micheloosterhof** [hpfeeds/hpfeeds#72]
Hello!
We're running into issues with the `hpfeeds` library and recent versions of Python.
This was reported here in Cowrie: https://github.com/cowrie/cowrie/issues/1969

The issue is this: https://stackoverflow.com/questions/74345065/attributeerror-module-asyncio-has-no-attribute-coroutine-in-python-3-11

In https://github.com/hpfeeds/hpfeeds/blob/master/hpfeeds/twisted/service.py

**Comment by Jc2k** [comment]
Thanks for letting me know. It looks like cowrie doesn't even need those methods, and cowrie was the main reason that wrapper was added.

They are a bit weird because they are trying to bridge twisted and asyncio worlds, so i can't just make them `async def`? I'm tempted to just remove at this point.

**Comment by Jc2k** [comment]
I've pushed `3.1.0` which removes `asyncio.Coroutine`. Can you test that out? I'll upgrade my own local cowries with it soon but it probably wont be for a couple of days.

**Comment by micheloosterhof** [comment]
I don't have an `hpfeeds` setup. maybe @D1sD3s ?

**Comment by D1sD3s** [comment]
I have tested it and i can confirm, that the version 3.1.0 of hpfeeds resolves this issue.

**Comment by micheloosterhof** [comment]
Thanks @D1sD3s , @Jc2k
